### ISSUE TITLE
SRE.fit does not save number of iterations and convergence status?

### ISSUE THREAD

**Issue by bzki** [andrewzm/FRK#1]
When running `SRE.fit` or `FRK`, you can feed in the parameter `n_em` to determine the maximum number of iterations. The progress bar tells you how far along the specified maximum number of iterations you have gone, and prints a message if you hit the maximum number. See https://github.com/andrewzm/FRK/blob/27a3967d70745df6f0cbdefa45162a4b50d074b4/R/SREutils.R#L391

But for someone analyzing model fits (possibly many) after the fact, it may be useful to allow the user to obtain the number of iterations `i` (and whether the maximum number was hit before there was convergence), or other relevant messages directly. 

Any thoughts on this? I can understand that this might break other behavior for functions that only expect an SRE model fit object to be returned, so I hesitate to request something that isn't useful to others and creates more problems. If there's an easier R workaround that saves the printed messages, perhaps I could simply use that method. 

```R
library(sp)
library(ggplot2)
library(FRK)
## Setup
set.seed(1)                                               # Fix seed
zdf <- Z <- data.frame(x = runif(1000), y= runif(1000))   # Generate random locs
zdf$z <- Z$z <- sin(8*Z$x) + cos(8*Z$y) + 0.5*rnorm(100)  # Simulate data
coordinates(Z) = ~x+y                                     # Turn into sp object

## Run FRK
S <- FRK(f = z~1,                             # Formula to FRK
         list(Z),                             # All datasets are supplied in list
         n_EM = 10)                           # Max number of EM iterations

## Possibly some behavior like the following
print(S@converge)
print(S@iterations)
print(S@messages)
```

**Comment by andrewzm** [comment]
Good idea, I'll try to implement this soon.

**Comment by andrewzm** [comment]
Please update from github. If you do `info_fit(S)` you now have all the statistics you need (but not the messages as these are just interpretations of the list returned by `info_fit()`).

	str(info_fit(S))
	List of 5
	 $ method             : chr "EM"
	 $ num_iterations     : int 10
	 $ sigma2fshat_equal_0: num 1
	 $ converged          : num 0
	 $ plot_lik           :List of 4
	  ..$ x   : int [1:10] 1 2 3 4 5 6 7 8 9 10
	  ..$ llk : num [1:10] -895 -863 -849 -838 -830 ...
	  ..$ ylab: chr "log likelihood"
	  ..$ xlab: chr "EM iteration"

**Comment by andrewzm** [comment]
Let me know if it works before I close!

**Comment by bzki** [comment]
Just tried it, works great. Thank you!
