### ISSUE TITLE
Supply k parameter for binomial and negative-binomial FRK

### ISSUE THREAD

**Issue by joao-pompeu** [andrewzm/FRK#4]
Dear contributors,

I am opening this issue in hope that it might help other users instead of e-mailing you directly. I am modeling point referenced count data, and possibly negative-binomial distribution could better fit my data. However, I am struggling to set up the k parameter, which is a vector of size parameters at each BAU. Can you explain how I supply it using a real application (Crime in Chicago, but as point referenced) as you did in the original publication?

Best regards,

João R.

**Comment by msainsburydale** [comment]
Hi João, thanks for opening this issue. The size parameters can be given either with the spatial data (as a field named "k_Z") or with the BAUs (as a field named "k_BAU").  Please see the example below. I've also improved the error message given when the size parameters are not provided, ready for the next update to CRAN. 

Best, 
Matt

```
library("FRK") 
library("sp") 

# Simulate data
m <- 250 # Sample size
zdf <- data.frame(x = runif(m), y = runif(m)) # Generate random locs
Y   <- sin(zdf$x) + cos(zdf$y)                # Latent Gaussian scale process
pi  <- plogis(Y)             # Latent probability process; squash Y onto the range (0, 1)
zdf$k_Z <- sample(1:30, m, replace = TRUE)  # size parameter (e.g., number of trials)
zdf$z   <- rbinom(m, zdf$k_Z, pi)             # Simulate binomial data
coordinates(zdf) = ~x+y                       # Turn into sp object

# Model fitting
S <- FRK(f = z ~ 1, list(zdf), 
         response = "binomial", link = "logit", 
         nonconvex_hull = FALSE)

# Prediction over the BAUs
pred <- predict(S) 
```
