### ISSUE TITLE
Question about temporal change of support for Fixed rank kriging in space and time

### ISSUE THREAD

**Issue by zzyzzyzzy** [andrewzm/FRK#5]
Dear contributors,

I have a question about the FRK in space and time. In the document of FRK in R, it said temporal change of support is not possible. Does that means temporal change of support is not possible for FRK model, or this feature has not been implemented yet, but it is possible theoretically?

Thanks for your reading,
Zhaoyuan

**Comment by andrewzm** [comment]
Definitely possibly theoretically. It's just that we haven't implemented
the functionality that observations are averages or aggregates "over time"
yet, just "over space". Note, you can have change of support over space in
a spatio-temporal model in FRK.

Andrew

**Comment by zzyzzyzzy** [comment]
Thanks for your explanation, Andrew.
